// Usage, from the repository root: dotnet run tools/IconImport/ImportIcons.cs
// Regenerates src/WpfFoundation/Themes/Icons.xaml from tools/IconImport/icons.txt: downloads each icon's
// 16 px Regular SVG from Fluent UI System Icons (MIT) and writes its outline as a StreamGeometry resource.
using System.Text;
using System.Text.RegularExpressions;

const string AssetsUrl = "https://raw.githubusercontent.com/microsoft/fluentui-system-icons/main/assets";
const string ListPath = "tools/IconImport/icons.txt";
const string OutputPath = "src/WpfFoundation/Themes/Icons.xaml";

var xaml = new StringBuilder();
xaml.Append("""
    <!--
        Generated by tools/IconImport/ImportIcons.cs from tools/IconImport/icons.txt; do not edit by hand.
        Outlines from Fluent UI System Icons (https://github.com/microsoft/fluentui-system-icons),
        MIT License, Copyright (c) 2020 Microsoft Corporation. See THIRD-PARTY-NOTICES.md.
        Each geometry is drawn on a 16 by 16 grid. Show it with WpfFoundation.Controls.PathIcon, or as the Tag of
        a button using WfIconContentTemplate.
    -->
    <ResourceDictionary xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
                        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml">


    """);

using var http = new HttpClient();
foreach (var line in File.ReadAllLines(ListPath))
{
    if (line.Length == 0 || line.StartsWith('#'))
    {
        continue;
    }

    var parts = line.Split('|', StringSplitOptions.TrimEntries);
    if (parts.Length != 2 || parts[0].Length == 0 || parts[1].Length == 0)
    {
        throw new FormatException($"Expected '<name> | <asset folder>' in {ListPath}: {line}");
    }

    var (name, asset) = (parts[0], parts[1]);
    var file = $"ic_fluent_{asset.ToLowerInvariant().Replace(' ', '_')}_16_regular.svg";
    var svg = await http.GetStringAsync($"{AssetsUrl}/{Uri.EscapeDataString(asset)}/SVG/{file}");

    if (!svg.Contains("viewBox=\"0 0 16 16\"", StringComparison.Ordinal))
    {
        throw new InvalidDataException($"{file} is not drawn on a 16 by 16 grid.");
    }

    var paths = Regex.Matches(svg, "<path\\b[^>]*>");
    if (paths.Count == 0 || Regex.IsMatch(svg, "<(?!/?(svg|path)\\b)[a-zA-Z]"))
    {
        throw new InvalidDataException($"{file} has shapes other than paths; convert it by hand.");
    }

    // One StreamGeometry has one fill rule: F1 is SVG's default nonzero rule, F0 is even-odd.
    var evenOdd = paths.Select(path => path.Value.Contains("fill-rule=\"evenodd\"", StringComparison.Ordinal)).Distinct().ToArray();
    if (evenOdd.Length > 1)
    {
        throw new InvalidDataException($"{file} mixes fill rules; convert it by hand.");
    }

    var data = string.Join(" ", paths.Select(path => Regex.Match(path.Value, "\\sd=\"([^\"]+)\"").Groups[1].Value));
    xaml.Append($"""
            <StreamGeometry x:Key="WfIcon{name}">{(evenOdd[0] ? "F0" : "F1")} {data}</StreamGeometry>

        """);
}

xaml.Append("</ResourceDictionary>\n");
File.WriteAllText(OutputPath, xaml.ToString().ReplaceLineEndings("\n"));
Console.WriteLine($"Wrote {OutputPath}.");
